import 'package:livekit_client/livekit_client.dart';
import 'livekit_config.dart';

/// Service for managing LiveKit video, audio and chat
class LiveKitService {
  late Room _room;
  bool _isConnected = false;

  /// Get room reference
  Room? get room => _isConnected ? _room : null;

  /// Check if connected
  bool get isConnected => _isConnected;

  /// Connect to LiveKit room
  Future<void> connectToRoom({
    required String roomName,
    required String participantName,
  }) async {
    try {
      // Create a new room
      _room = Room();

      // Get access token from LiveKit server
      // In production, this should be generated by your backend server
      final token = await _generateAccessToken(
        roomName: roomName,
        participantName: participantName,
      );

      // Connect to room
      await _room.connect(
        LiveKitConfig.liveKitUrl,
        token,
        connectOptions: ConnectOptions(
          autoSubscribe: true,
        ),
      );

      _isConnected = true;
      _setupRoomEventListeners();
    } catch (e) {
      _isConnected = false;
      throw Exception('Failed to connect to LiveKit: $e');
    }
  }

  /// Disconnect from room
  Future<void> disconnectFromRoom() async {
    if (_isConnected) {
      await _room.disconnect();
      _isConnected = false;
    }
  }

  /// Toggle microphone
  Future<void> toggleMicrophone(bool enabled) async {
    if (_isConnected) {
      final localParticipant = _room.localParticipant;
      if (localParticipant != null) {
        await localParticipant.setMicrophoneEnabled(enabled);
      }
    }
  }

  /// Toggle camera
  Future<void> toggleCamera(bool enabled) async {
    if (_isConnected) {
      final localParticipant = _room.localParticipant;
      if (localParticipant != null) {
        await localParticipant.setCameraEnabled(enabled);
      }
    }
  }

  /// Send text message via DataPacket
  Future<void> sendChatMessage(String message) async {
    if (!_isConnected) return;

    try {
      final localParticipant = _room.localParticipant;
      if (localParticipant != null) {
        await localParticipant.publishData(
          message.codeUnits,
          reliable: true,
          topic: 'chat',
        );
      }
    } catch (e) {
      throw Exception('Failed to send message: $e');
    }
  }

  /// Set up room event listeners
  void _setupRoomEventListeners() {
    // LiveKit event handling is available through Room callbacks
    // The specific events will be handled by the application level
    // Debug: Room event listeners initialized
  }

  /// Generate access token (in production, call your backend)
  Future<String> _generateAccessToken({
    required String roomName,
    required String participantName,
  }) async {
    // In a production environment, you should call your backend API
    // to generate tokens securely. This is a placeholder.
    // For now, throw an exception to remind developers to implement this
    throw Exception(
      'Token generation not implemented. Please implement this in your backend.',
    );
  }

  /// Dispose resources
  Future<void> dispose() async {
    await disconnectFromRoom();
  }
}

